### ISSUE TITLE
这个怎么解决

### ISSUE THREAD

**Issue by lfx923** [PaulXu-cn/go-mod-graph-chart#1]
执行安装命令：go get -u github.com/PaulXu-cn/go-mod-graph-chart/gmchart
报错：package google.golang.org/protobuf/proto
        imports google.golang.org/protobuf/proto: import cycle not allowed

**Comment by PaulXu-cn** [comment]
你新开一个目录，把这个仓库clone到新目录内，在这个git项目内 go install 试试看呢。

我估计你运行 go get 这个命令的环境，与当前的项目依赖冲突了。
