### ISSUE TITLE
如何区分直接依赖和间接依赖？

### ISSUE THREAD

**Issue by txlong2012slug** [PaulXu-cn/go-mod-graph-chart#11]
- 如何区分直接依赖和间接依赖？
- 不同颜色代表什么含义？

**Comment by PaulXu-cn** [comment]
1. 直接or间接依赖，看 go.mod 文件，包后面带 `// indirect` 表示为间接依赖。
2. 这个库渲染了一个左为根，右为枝叶的树状结构。同一层级，有同父节点的为同色。不同色是为了好区分那些有海量子节点的，一个屏幕展示不完的情况。
