### ISSUE TITLE
command not found: gmchart

### ISSUE THREAD

**Issue by wangliguokaka** [PaulXu-cn/go-mod-graph-chart#13]
mac 电脑上执行 提示找不到命令，如下图：
![image](https://github.com/PaulXu-cn/go-mod-graph-chart/assets/17798088/5d2440eb-67b4-4d4d-8917-f939c9589e7b)

**Comment by PaulXu-cn** [comment]
看这个报错信息，你应该是没有安装上。报错信息不是我抛的，你可以看看——[go issues](https://github.com/golang/go/issues/34499)

如果不管这个报错信息，可以这样：
你已经clone仓库到本地了，可以在当前目录执行：
```shell
$ go install ./gmchart 
```
这样就能编译并安装到 `go/bin` 目录了
