### ISSUE TITLE
GET is not allowed

### ISSUE THREAD

**Issue by chuckchann** [PaulXu-cn/go-mod-graph-chart#14]
{"code":"MethodNotAllowed","message":"GET is not allowed"}
点击链接后展示这个 麻烦看下是怎么回事

**Comment by PaulXu-cn** [comment]
请详细阐述下，在什么情况下，点击了什么链接展示了这个？以及怎么展示的。
你周围有朋友用这个工具么？他们怎么说

**Comment by chuckchann** [comment]
> 请详细阐述下，在什么情况下，点击了什么链接展示了这个？以及怎么展示的。 你周围有朋友用这个工具么？他们怎么说

现在又可以了... 另外 方便问下怎么将go mod graph 输出的内容构造成一个树型的结构？看go mod graph 输出的广度优先的结构

**Comment by PaulXu-cn** [comment]
这个程序输出的结果就是树状结构，你要获取json格式可以通过http接口访问，
```shell
$ curl http://127.0.0.1:xxxx/tree.json
```
广度优先是遍历算法，你说的是啥结构？

**Comment by chuckchann** [comment]
> 这个程序输出的结果就是树状结构，你要获取json格式可以通过http接口访问，
> 
> ```shell
> $ curl http://127.0.0.1:xxxx/tree.json
> ```
> 
> 广度优先是遍历算法，你说的是啥结构？

谢谢回答 我大概知道了
