### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Nomamuk** [PaulXu-cn/go-mod-graph-chart#5]
![image](https://user-images.githubusercontent.com/26339608/130622765-7fc1b94e-97e6-4c60-96a3-74cfe9ec1a9f.png)

**Comment by greatming** [comment]
同问

**Comment by envestcc** [comment]
同问

**Comment by Arthur-Meng** [comment]
同问

**Comment by chuailiwu** [comment]
same question

**Comment by debug-LiXiwen** [comment]
goroutine 1 [running]:
github.com/PaulXu-cn/go-mod-graph-chart/gosrc.BuildTree(0xc0007da000, 0x5ba1c, 0x4d4, 0xc0002440e8, 0x401)
        /Users/ll/go/pkg/mod/github.com/!paul!xu-cn/go-mod-graph-chart@v0.5.0/gosrc/treeutil.go:103 +0x85d
main.main()
        /Users/ll/go/pkg/mod/github.com/!paul!xu-cn/go-mod-graph-chart@v0.5.0/gmchart/main.go:103 +0x551
