### ISSUE TITLE
panic : runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sunzip** [PaulXu-cn/go-mod-graph-chart#6]
go mod graph | gmchart
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x3d4a1d]

goroutine 1 [running]:
github.com/PaulXu-cn/go-mod-graph-chart/gosrc.BuildTree(0xc00024a000, 0x1a796, 0x209, 0xc0002c30e8, 0x201)
        C:/Users/xxx.sun/go/pkg/mod/github.com/!paul!xu-cn/go-mod-graph-chart@v0.5.0/gosrc/treeutil.go:103 +0x87d
main.main()
        C:/Users/xxx.sun/go/pkg/mod/github.com/!paul!xu-cn/go-mod-graph-chart@v0.5.0/gmchart/main.go:103 +0x571

**Comment by francisLee777** [comment]
+1

**Comment by wgkflyit** [comment]
+1

**Comment by romberli** [comment]
+1

**Comment by zhijian-pro** [comment]
+1

**Comment by Chengxiangrong** [comment]
+1

**Comment by brzyangg** [comment]
+1

**Comment by Cherryfla** [comment]
+1

**Comment by Jeremy-boo** [comment]
+1

**Comment by quwang123** [comment]
+1

**Comment by zxz0622** [comment]
pull latest version with: go get -u github.com/PaulXu-cn/go-mod-graph-chart/gmchart@main
