### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by quan-ouyang** [PaulXu-cn/go-mod-graph-chart#8]
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/PaulXu-cn/go-mod-graph-chart/gosrc.BuildTree(0x1256c000, 0x3eedd, 0x3a2, 0x12620934, 0x201, 0x12630000)
        C:/Users/admin/go/pkg/mod/github.com/!paul!xu-cn/go-mod-graph-chart@v0.5.0/gosrc/treeutil.go:85 +0xba9
main.main()
        C:/Users/admin/go/pkg/mod/github.com/!paul!xu-cn/go-mod-graph-chart@v0.5.0/gmchart/main.go:103 +0x415

**Comment by wangriyu** [comment]
+1

**Comment by rsgok** [comment]
+1

**Comment by wangpin34** [comment]
Same error.  Any updates?

**Comment by liu-jianhao** [comment]
+1

**Comment by mafulong** [comment]
+1,
